services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --protected-mode no
    networks:
      - coolify

  stremio-translate:
    build: .
    volumes:
      - subtitles-data:/app/subtitles
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  subtitles-data:
