services:
  stremio-translate:
    build: .
    volumes:
      - subtitles-data:/app/subtitles
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  subtitles-data:
