services:
  stremio-worker:
    build: .
    command: node worker.js
    volumes:
      - subtitles-data:/app/subtitles
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  subtitles-data:
    external: true
